name: my First workflow 

on:  push 
jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps: 
        
        - name: checkout repo 
          uses: actions/checkout@v5
        - name: welcome message 
          run: echo "my first Github actions job"
        
        # - name: move README file
        #   run: mv README.md > msg.txt 
        
        - name: give msg.txt permissions 
          run: chmod +x msg.txt 

        - name: list files 
          run: ls -ltr

        - name: Read files 
          run: cat README.md